### ISSUE TITLE
v2.x

### ISSUE THREAD

**Issue by metamindxx** [JLynch7/SlickGrid#1]
Hi,

Looks like you have done a great job.

I am using the latest version of SlickGrid which seems v. different to the 1.4 branch you have based this on. Do you have any plans on merging your changes forward (or getting the main branch of SG to include them).

Thanks

**Comment by JLynch7** [comment]
I've updated my gh-pages with the 2.0 version from my branch:  https://github.com/JLynch7/SlickGrid/tree/2.0-frozenRowsAndColumns

There is at least 1 minor known issue.  Let me know what you think.

**Comment by metamindxx** [comment]
That's looking pretty cool. One thing though. I had a row of column headings that had totals in them. I did this by adding:

```
showHeaderRow: true,
```

into the "options" object.

I populated them using:

```
        function updateHeaderRow() {
            var val
            for (var i = 0; i < columns.length; i++) {
                    var header = grid.getHeaderRowColumn(columns[i].id);
                    $(header).outerWidth(columns[i].width);
                    $(header).empty()
                    if (j.totals[columns[i].id]) {
                        val = j.totals[columns[i].id].formatMoney()
                    } else {
                        val = ''
                    }

                    $('<div class="cell-total cell-currency">' + val + '</div>')
                        .appendTo(header);
            }
        }
```

But now they don't show anything. 

Still investigating, but if you know why this might happen I would be v. interested.

Thanks.

**Comment by metamindxx** [comment]
Sorry. Closed it by mistake.

Also, the scroll bar across the bottom (I am freezing columns) seems to move off the edge of the screen. It looks to me that the amount that it goes off by is about the same as the width of the columns that are fixed.

Cheers.

**Comment by JLynch7** [comment]
I was able to reproduce your issue and fixed it in https://github.com/JLynch7/SlickGrid/commit/549246ecaf2225db579156c4392743f139cf711e

Let me know if that doesn't fix your problem

**Comment by metamindxx** [comment]
Brilliant job on the headings. Works like a charm.

Scroll bar is still a bit funny though.

**Comment by metamindxx** [comment]
Oh and just noticed that the vertical scroll bar is missing. It is probably off to the right of the screen. I suspect it is linked to the horizontal scroll bar issue. I think the right pane thinks it is the same width as the whole screen would be if the fixed columns weren't there. I will investigate.

**Comment by JLynch7** [comment]
Can you help me understand how you render the grid?  I'm having trouble reproducing the issue.  If you have a screenshot or can upload a code example to http://jsfiddle.net/ that would help too.

**Comment by metamindxx** [comment]
Yup. I have columns that represent months. I must have about 30 columns. 

```
        var columns = [
            {id:"sel", name:"#", field:"id", behavior:"select", cssClass:"cell-selection", width:40, cannotTriggerInsert:true, resizable:false, selectable:false },
            {id:"un", name:"used name", field:"un", minWidth:120, cssClass:"cell-title", sortable:true},
            {id:"sn", name:"surname", field:"sn", minWidth:120, cssClass:"cell-title", sortable:true},
            {id:"status", name:"status", field:"status", minWidth:120, cssClass:"cell-title", sortable:true},
            {id:"start", name:"Start", field:"start", minWidth:60, editor:DateCellEditor, sortable:true},
            {id:"total", name:"Total", field:"sum", minWidth:10, formatter:currencyFormatter, cssClass:"cell-currency", sortable:true},
        ];


        // add the month columns
        while(y + m/100 < yTo + mTo/100) {
            if (m < 10) {
                ds = y + "-0" + m
            } else {
                ds = y + "-" + m
            }
            columns.push({id:ds, name:ds, field:ds, minWidth:40, formatter:currencyFormatter, cssClass:"cell-currency", sortable:true, groupTotalsFormatter:sumTotalsFormatter})
            m = m - 0 + 1
            if (m == 13) {
                y = y - 0 + 1
                m = 1
            }
        }
```

The grid takes up the whole width of the screen and there are more columns than can fit on the grid.

**Comment by JLynch7** [comment]
Can you provide a bit more information.  Such as what are y, m, yTo & mTo defined as?  What is your container div width for the grid set to?

**Comment by metamindxx** [comment]
"j" is the ajax JSON object that comes down over the wire. An example of the dates part of it is:

  j.dates: {from:2008-10, to:2012-09}

Then a column is added to the grid for each month in the date range so in the "// add the month columns" loop above: 
  y iterates over the years,
 m iterates over the months

```
        var dFrom = j.dates.from.split('-')
        var dTo = j.dates.to.split('-')
        var y = dFrom[0] - 0  // the current year
        var m = dFrom[1] - 0  // the current month
        var yTo = dTo[0] - 0  // the final year
        var mTo = dTo[1] - 0  // the final month
        var ds  // date string
```

For the test on the "while" loop I make a decimal out of the year and month that looks something like 2011.06 and 
compare the current month to the final month to see whether we have finished.

ds is the "date string" that looks something like "2011-06" and is used as the column id, name and field.

The grid is set up in html like this:

```
        <div id="myGrid" style="width:100%;height:500px;"></div>
```

**Comment by JLynch7** [comment]
Thanks.  I was able to reproduce the issue and fixed it in https://github.com/JLynch7/SlickGrid/commit/bee03e6448a61f1893910b6029e8a20ae69599ec

**Comment by metamindxx** [comment]
perfect. great job!
