### ISSUE TITLE
Resizing column headers doesnt work properly

### ISSUE THREAD

**Issue by slubowsky** [JLynch7/SlickGrid#10]
After latest merge, behavior when column headers is resized is incorrect. Different bad behavior depending on which column is resized. Often you can cause a space to appear between frozen and unfrozen columns, can lose "line" dividing frozen column header and unfrozen column header, have also seen columns get out of sync with column headers.

Easily reproducible by running the example-frozen-columns.html in IE9 (didn't try any other browsers) and just randomly resizing various column headers

**Comment by slubowsky** [comment]
Much better now, but still get strange behavior if force fit columns or synchronous resize is checked
(also recommend adding 2 new column picker options and check for options.autoResize || options.syncResize in slick.columnpicker.js handleHeaderContextMenu function as appropriate before adding those checkboxes to the column picker - I don't find those options useful in my context)

**Comment by JLynch7** [comment]
I made a small change, see if that helps.  If not, can you describe in a bit more detail what you're experiencing?

**Comment by slubowsky** [comment]
Synchronous resize does seem to work correctly. Force fit columns though does not. With that checked, I find that resizing the frozen column to be smaller seems to for some reason make the first unfrozen column header a corresponding amount larger (instead of moving it to the left) and only the column header, not the column, so the headers and columns are now completely out of alignment. If I make the frozen column larger, it shrinks the unfrozen column headers to a minimum size one by one as I drag the frozen column header larger - but does not move them to the right as they should. When I stop dragging, the columns each become some large size, and are now out of sync with the column headers.

**Comment by alanchowky** [comment]
I have similar issue when upgrading the grid. 

And I found that the grid structure changed a bit...

in the new example, i found there is one more div added.

Hope it helps.

**Comment by JLynch7** [comment]
@slubowsky I just merged a couple changes that should fix the forceFitColumns issue you are encountering.  The header columns still look a little strange while resizing, but the rows look good once you stop dragging.  

Give it a test and let me know what you think.

**Comment by slubowsky** [comment]
Definitely better. Thank you. As you mention though, still looks strange as its being dragged

**Comment by JLynch7** [comment]
All column resizing bugs have been fixed in 1dffc84d43bbb084d5e4ba0bcdabf5ea8a7fd5ef
