### ISSUE TITLE
Row Reorder with Frozen Column

### ISSUE THREAD

**Issue by kengineer** [JLynch7/SlickGrid#11]
I am not able to get row reordering with a frozen column to work. I have a hunch this isn't possible, so before I painstakingly try to figure it out only to raise the white flag in defeat, I was wondering if you could give me a "yeh" or "neh" on being able to do this. All I've done so far is just add the "frozenColumn: 0" grid option to the row reordering example and got no love in return.

Thanks!

**Comment by kengineer** [comment]
Ok, so the error I was getting was on line 375 of slick.grid.js where it states...

$viewportTopL.mousewheel(handleMouseWheel);

if I comment that out, it seems to work. Obviously that probably breaks other things so I more robust solution is needed, but at least I have a temporary work around.

**Comment by JLynch7** [comment]
The error is caused because you're missing the mousewheel library.  If you add ../lib/jquery.mousewheel.js to your JS includes, your page should load.

I've briefly looked into this and it looks like I still have some merge clean up to do.

**Comment by kengineer** [comment]
Ok, that was the problem. Thanks!
