### ISSUE TITLE
Mliebman added new code to SlickGrid 3 days ago, will you be updating?

### ISSUE THREAD

**Issue by CoffeeJerk** [JLynch7/SlickGrid#12]
Mliebman added new code, specifically a new function called scrollRowToTop() among other changes. Will you be updating your locking column branch to match his updates?

**Comment by JLynch7** [comment]
If that's the only commit you need, I can cherry pick it and merge it in tonight when I get home.

**Comment by CoffeeJerk** [comment]
Anything you can do is wonderful and greatly appreciated. We do need that function, but we are also interested in some of the other functions and fixes that Liebmann has committed. My general question was more about whether you try to stay in synch with him, and if so how far behind him you like to stay.
Thanks so much and again, great work!
- Mike

On Jun 4, 2012, at 3:02 PM, JLynch7 wrote:

> If that's the only commit you need, I can cherry pick it and merge it in tonight when I get home.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/JLynch7/SlickGrid/issues/12#issuecomment-6107360

Michael Berger
Senior User Interface Designer and Developer
mberger@mit.edu

**Comment by JLynch7** [comment]
I don't necessarily have a specific time frame.  It's more related to the amount of effort required to do the merge.  The latest  major merge I worked on still isn't 100% (I'm still working on issue #10).

Anyways, I've picked 3 commits that were easy to merge.  Let me know if you find any issues.

**Comment by CoffeeJerk** [comment]
Thanks so much!
- Mike
  On Jun 4, 2012, at 8:43 PM, JLynch7 wrote:

> I don't necessarily have a specific time frame.  It's more related to the amount of effort required to do the merge.  The latest  major merge I worked on still isn't 100% (I'm still working on issue #10).
> 
> Anyways, I've picked 3 commits that were easy to merge.  Let me know if you find any issues.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/JLynch7/SlickGrid/issues/12#issuecomment-6115207

Michael Berger
Senior User Interface Designer and Developer
mberger@mit.edu
