### ISSUE TITLE
autoHeight = true option doesn't work

### ISSUE THREAD

**Issue by kengineer** [JLynch7/SlickGrid#13]
We are currently replacing the mleibman slickgrid with yours to take advantage of the column freezing feature. However, some of our grids do not have an explicit height set on the div, but instead set the autoHeight option to true when initializing the grid. This results in the grid not showing up after the switch. Upon inspecting the dom, the data is all there, it just doesn't show up because the grid has no height.

The best way to reproduce is to take the the example1-simple.html example and add autoHeight=true to the grid options and remove the 500px height from the div with the id "myGrid".

**Comment by JLynch7** [comment]
Fixed in 6c3eb70ed4f5a808cbdc588b870cf5d51f4f8e51
