### ISSUE TITLE
autoHeight = true with frozen column doesn't work

### ISSUE THREAD

**Issue by kengineer** [JLynch7/SlickGrid#14]
I tried the latest fix that fixed the autoHeight = true issue, but when using it with the frozenColumn option, no columns are frozen (or at least no horizontal scroll bars are shown). Also the scroll bar on the right of the grid (which really isn't necessary) acts a little weird (behavior differs between chrome and FF).

To reproduce, take the example-frozen-columns.html example and do the following:
1. Remove the style height from the myGrid div.
2. Add autoHeight = true to the grid options.
3. Reduce the number of data elements from 50000 to 25 or something smaller (Optional but makes it easier to test).

**Comment by JLynch7** [comment]
Fixed in 73254fd223157617f420930444b960bc9145e2b5.  Please test and let me know your results

**Comment by kengineer** [comment]
Looks to be working. Thanks!
