### ISSUE TITLE
Column Resizing with Frozen Column Issue

### ISSUE THREAD

**Issue by kengineer** [JLynch7/SlickGrid#15]
I noticed an issue when I resize a column when columns our frozen. When I try to resize a column, the column before the one I want to resize is actually the one resized. 

To duplicate for the column resizing eample (http://jlynch7.github.com/SlickGrid/examples/example-frozen-columns.html) do the following. 
1. Resize the "% Complete" Column. The Duration column is resized instead.

The weird thing is that it only seems to be a problem for some columns. I noticed this behavior with the "% Complete" and "Effort Driven" columns, but other columns work as expected.

**Comment by JLynch7** [comment]
I believe what you're experiencing is by design.  Try resizing the '% Complete" column on mleibman's Example 4 (http://mleibman.github.com/SlickGrid/examples/example4-model.html)

If you still feel there is a bug, I'll take a deeper look.

**Comment by JLynch7** [comment]
Any update on this?

**Comment by kengineer** [comment]
Sorry, was away on vacation :-) You're right; that seems to be the intended behavior.
