### ISSUE TITLE
Space on right with no frozen columns

### ISSUE THREAD

**Issue by CoffeeJerk** [JLynch7/SlickGrid#16]
It appears that when 'forceFitColumns' option is set to true, the calculations in getCanvasWidth() are not correct for grids that require vertical scrolling and have no frozen columns (frozenColumn: -1). This ultimately leads to extra empty space on the right.

**Comment by JLynch7** [comment]
Can you reproduce with one of the examples?  I looked at http://jlynch7.github.com/SlickGrid/examples/example4-model.html and I don't see anything wrong.

**Comment by CoffeeJerk** [comment]
Jason:
To reproduce, I took this example:http://mleibman.github.com/SlickGrid/examples/example5-collapsing.html
I pulled the grid html (id=mygrid) out of the table and set the outer div's width to 60% (any percentage width will do). Then I switched the slick.grid.js to your branch that handles locking columns. And viola, space on the right side of the grid appears.
Because of our design we have hierarchical grids with percentage-width divs.
Thanks for looking at this, 
- Mike

On Jun 19, 2012, at 8:40 PM, JLynch7 wrote:

> Can you reproduce with one of the examples?  I looked at http://jlynch7.github.com/SlickGrid/examples/example4-model.html and I don't see anything wrong.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/JLynch7/SlickGrid/issues/16#issuecomment-6442183

Michael Berger
Senior User Interface Designer and Developer
mberger@mit.edu

**Comment by JLynch7** [comment]
I'm sorry, I still cannot reproduce this.  Can you attach/send me a screen shot or create a http://jsfiddle.net/ ?

**Comment by CoffeeJerk** [comment]
Interesting, I can't reproduce it today the way I described to you either. We definitely have it in our code, so I am sending screen shots. I have console.logged slick.grid.js, which you will see in the screen shots. The problem occurs when updateCanvasSize is called twice for each grid. The first time it reads the correct width, the second time it reads 17 pixels less.
FYI, slick.grid4.js is your most recent frozen column branch. I renamed it to keep track for ourselves.
Thanks for looking at this.
It is quite likely a problem with our css code, or our css in combination with the slick grid width calculator.

On Jun 21, 2012, at 11:38 PM, JLynch7 wrote:

> I'm sorry, I still cannot reproduce this.  Can you attach/send me a screen shot or create a http://jsfiddle.net/ ?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/JLynch7/SlickGrid/issues/16#issuecomment-6499970

Michael Berger
Senior User Interface Designer and Developer
mberger@mit.edu

**Comment by JLynch7** [comment]
Is this still an issue?

**Comment by CoffeeJerk** [comment]
One of your last releases fixed this issue. We are no longer experiencing this issue. Thank you! You can close this ticket.

##    - Mike

Michael Berger
Senior User Interface Designer and Developer
Data Management/Business Intelligence Team
Office Phone: 617-253-0683
Email: mberger@mit.edu
