### ISSUE TITLE
Frozen columns hangs when Mouse Scroll Down at the bottom

### ISSUE THREAD

**Issue by alanchowky** [JLynch7/SlickGrid#17]
You can reproduce by dragging to the bottom and try scrolling up and down using mouse wheel.

http://jlynch7.github.com/SlickGrid/examples/example-frozen-columns.html

**Comment by JLynch7** [comment]
I believe this is fixed in b8b4c079be4a3d52a1aed64a3ec9b3664762d418,  please test and let me know

**Comment by alanchowky** [comment]
The hanging problem is fixed. 

there is still a bit strange:
1. when the grid has vertical scrollbar (in my case, fixed height grid with many rows), the last row is block by the horizontal scrollbar.
2. The forzon columns scroll down is very insensitive........(but scroll up is ok)

**Comment by laurencei** [comment]
I was coming here to report this EXACT bug. The fix above is working for me - thanks so much!

**Comment by JLynch7** [comment]
@alanchowky check out 3e72136d11f70302f5f0cbb43168070e1fdd2765 and let me know how it looks.

**Comment by JLynch7** [comment]
Check out the latest commit and let me know if its now working as expected

**Comment by alanchowky** [comment]
Yes. It work as expected. 
Thanks a lot.
