### ISSUE TITLE
Lower left and right rows do not match when scrolled to the bottom

### ISSUE THREAD

**Issue by igorT** [JLynch7/SlickGrid#18]
How to reproduce:
Open example example-frozen-columns-and-rows.html
Scroll all the way to the bottom, press the up or down arrow on the scrollbar and move around. When you are at the last row, the rows are mismatched.

**Comment by igorT** [comment]
Awesome. Any chance you could remove the stutter that happens when scrolling down while your mouse focus is on the right column?

**Comment by igorT** [comment]
@JLynch7 ?

**Comment by JLynch7** [comment]
Have you confirmed if this is still a problem with the latest commit?

**Comment by igorT** [comment]
Latest commit fixed it. Thanks!
