### ISSUE TITLE
Mouse hover does not extend for all rows

### ISSUE THREAD

**Issue by igorT** [JLynch7/SlickGrid#19]
How to reproduce:
Make rows highlight when hovering.
Highlight is only applied to the left or right pane but not the entire row.

**Comment by JLynch7** [comment]
What method are you using to enable row highlighting when hovering?

**Comment by igorT** [comment]
I used css:hover which obviously broke now that I moved to frozen columns. Do you have a suggestion how to easily implement per row properties or events like that?

**Comment by JLynch7** [comment]
I've updated the examples to show how to enable row highlighting.  See commit 4cb9f0c4c7baee0f5a6c23e402b10606cf734446.  Let me know if that works for you.

**Comment by igorT** [comment]
Ended up doing almost that, but with css classes as I also needed a separate select as well.
Thanks for the example though.
