### ISSUE TITLE
Rows offset between frozen and non-frozen columns when editing non-frozen cell in Chrome

### ISSUE THREAD

**Issue by shiftyp** [JLynch7/SlickGrid#2]
## Description

With one or more frozen columns enabled, rows become offset between the frozen and non-frozen column when an editor is opened for a non-frozen column cell.  This is an issue in Google Chrome only, and does not occur in Firefox or IE.
## Version

f5b7d77d414380fe1c418c593a20c72d8c0a93e2
## Browsers

Google Chrome (15.0.874.106)
## Steps to reproduce
1. Open [frozen columns example](http://jlynch7.github.com/SlickGrid/examples/example-frozen-columns.html) in Google Chrome.
2. Edit a cell in a non-frozen column.

**Comment by JLynch7** [comment]
Fixed in https://github.com/JLynch7/SlickGrid/commit/170124f2fd60171fce0f0aedee838a90a7b14877

Please verify

**Comment by shiftyp** [comment]
Yep, works great.  Thanks.
