### ISSUE TITLE
Row Selection Shifted when there is vertical scrollbar

### ISSUE THREAD

**Issue by alanchowky** [JLynch7/SlickGrid#24]
I have tested in Chrome and IE9. Both browsers have same problem.

To reproduce it, reduce the height of the browser to make the vertical scrollbar visible (i.e. there is a vertical scrollbar of the body tag), you drag vertical scrollbar of the body tag to the bottom.

After that, you click in the middle of the grid and you will see the selection is shifted....

http://jlynch7.github.com/SlickGrid/examples/example-frozen-columns.html

**Comment by JLynch7** [comment]
Please verify the latest commit fixes this and let me know

**Comment by alanchowky** [comment]
Yes. It fixes the problem.
