### ISSUE TITLE
Error removing column

### ISSUE THREAD

**Issue by slubowsky** [JLynch7/SlickGrid#27]
FYI - With latest code removing a column by unchecking it in the column picker results in an error. For example go to:
http://jlynch7.github.com/SlickGrid/examples/example-frozen-columns.html
right click in columns and uncheck the checkbox for title
Error - on slick.columnpicker.js line 102 - _self is not defined

**Comment by slubowsky** [comment]
Aside from that (easily fixed of course - just add back missing var _self = this; in constructor) seems to be working very well.

**Comment by JLynch7** [comment]
This was resolved in the latest commit by aligning slick.columnpicker.js file with mleibman's repo
