### ISSUE TITLE
grid is not displaying properly when embedded in tabs

### ISSUE THREAD

**Issue by michaelbella** [JLynch7/SlickGrid#28]
The frozen columns and rows are really great. Thanks for creating this branch.
I am embedding multiple grids in a JQuery Tab UI element. The grids are created and populated dynamically. In the first tab, everything works great. But in the other tabs, the grid only shows the first couple columns, and the rest is blank. This occurs whether there are frozen elements or not. The exact same code looks correct with the slickgrid Trunk.
Screenshot is here: http://tinypic.com/r/2f092xj/6

Thanks for your help!

**Comment by JLynch7** [comment]
I'm not able to reproduce this using the latest commit.  Can you verify this is still an issue?

**Comment by michaelbella** [comment]
My problem is fixed with this update. Thanks!

On Tue, Nov 20, 2012 at 7:45 PM, JLynch7 notifications@github.com wrote:

> I'm not able to reproduce this using the latest commit. Can you verify
> this is still an issue?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/JLynch7/SlickGrid/issues/28#issuecomment-10581175.

## 

michael.bell@acm.org
