### ISSUE TITLE
resizeCanvas does not take into account frozen columns

### ISSUE THREAD

**Issue by vprorok** [JLynch7/SlickGrid#29]
After window resize,  resizeCanvas is, in case there are frozen columns, not properly calculating grid's width.

**Comment by vprorok** [comment]
I managed to fix this issue with following change:

inside function updateCanvasWidth

 line: $viewportTopR.width(viewportW - canvasWidthL);

replaced with: $viewportTopR.width($viewportTopR.parent().width()- canvasWidthL);

**Comment by JLynch7** [comment]
Can reproduce this issue with one of examples?

**Comment by vprorok** [comment]
example12-fillbrowser.html ... this one has problem with height when resizing.... try adding frozen columns and you will see problem with width as well

**Comment by JLynch7** [comment]
Please test the latest commit.

**Comment by vprorok** [comment]
Seems to works fine.
Thx
