### ISSUE TITLE
frozenRow & frozenColumn is not competitive with multi-cells selection

### ISSUE THREAD

**Issue by lingyulin** [JLynch7/SlickGrid#31]
frozenRow & frozenColumn is not competitive with multi-cells selection
change example3-editing.html like below
var options = {
    editable: true,
    enableAddRow: true,
    enableCellNavigation: true,
    asyncEditorLoading: false,
    frozenColumn: 0,
    frozenRow: 1,
    autoEdit: true,
    frozenBottom:true
  };
select cells with your mouse
and the rect of the cells is not correct

**Comment by JLynch7** [comment]
This is fixed in the latest commit.  Please check it and let me know.
