### ISSUE TITLE
 rowsCache[activeRow] is undefined

### ISSUE THREAD

**Issue by cflocation** [JLynch7/SlickGrid#33]
I am getting this error when using the cell editors. It only happens after I enter the edit state on a row in a cell then scroll down to select a different row. You must scroll off the current screen of rows to get the error message.

This also happens on the example @ http://jlynch7.github.com/SlickGrid/examples/example-frozen-columns.html

Here is the full firebug error

TypeError: rowsCache[activeRow] is undefined
[Break On This Error]   

rowsCache[activeRow].rowNode.removeClass("active");

Any help would be appreciated.

Thanks

**Comment by JLynch7** [comment]
I'm not able to reproduce this.  Can you provide more detail?
