### ISSUE TITLE
rows cache not cleared

### ISSUE THREAD

**Issue by akovac** [JLynch7/SlickGrid#37]
Hi,

There is a bug in cleanupRows() method, removeFrozenRow flag logic should be reversed. It should be initialized to true and set to false within condition bellow.

**Comment by JLynch7** [comment]
How did you confirm this?

**Comment by akovac** [comment]
I don't use frozenRows in my setup, only frozen columns. So removeFrozenRow will always be false and cache never cleared. You can just try to navigate up/down via keyboard or scroll. You can put console.log into removeRowFromCache() to see if rows are actually removed from DOM. Also, you can use Chrome heap profiler. Take heap snapshot, scroll over all rows and take another heap snapshot. compare last with first snapshot and look for HTMLDivElement. You will see large Delta e.g. +1230.

**Comment by JLynch7** [comment]
Thanks for the nice catch. Can you verify this issue is resolved?

**Comment by akovac** [comment]
Hi, thanks. Tested with my code and your frozen row example and seems to be working fine now, I think you can close this issue. I noticed that there is possibly something strange with rangeToKeep.top and rangeToKeep.bottom calculation but I'm not sure at the moment I'll take a better look when I catch time.
