### ISSUE TITLE
Scrolling the frozen columns does not scroll the non-frozen columns

### ISSUE THREAD

**Issue by shiftyp** [JLynch7/SlickGrid#4]
There are two parts to this issue:
1. Mousewheel events on the frozen columns do not scroll either the non-frozen or frozen columns.  This can be tested in the [frozen columns example](http://jlynch7.github.com/SlickGrid/examples/example-frozen-columns.html).
2. Scrolling the frozen columns does not scroll the non-frozen columns.  The only way to scroll the frozen columns by themselves is to click within the frozen column and drag the mouse below or above the canvas.  Doing so scrolls the frozen columns without scrolling the non-frozen columns.  This can also be tested in the [frozen columns example](http://jlynch7.github.com/SlickGrid/examples/example-frozen-columns.html).

**Comment by JLynch7** [comment]
Should be fixed in https://github.com/JLynch7/SlickGrid/commit/2f430d68b6eb6233ba1b4c68ab1e2d240ca54889

Please test and let me know

**Comment by JLynch7** [comment]
I assume this is resolved

**Comment by shiftyp** [comment]
Sorry, yes it has been fixed. Thanks.
