### ISSUE TITLE
Canvas not scaling correctly, if width 100%

### ISSUE THREAD

**Issue by elGecko** [JLynch7/SlickGrid#5]
My canvas didn't scale correctly to the full width of the div, but rather only to about 100px. After some investigation I found out that viewportW = parseFloat($.css($container[0], "width", true)); returns 101,xx, but not the real width of my div. 

I then discovered that my div looks like this  <div id="myGrid" style="width:100%; height:350px;"></div>

Chaning it to absolute values, e.g.  <div id="myGrid" style="width:800px;height:350px;"></div> fixed that. However, this only happens if frozenColumn: 0. If it is 1 or bigger, this issue does not occur.

**Comment by JLynch7** [comment]
Typically the myGrid div is wrapped by another div with an absolute width.
e.g.

<div style="width:600px;">
            <div class="grid-header" style="width:100%">
                <label>SlickGrid</label>
                <span style="float:right" class="ui-icon ui-icon-search" title="Toggle search panel" onclick="toggleFilterRow()"></span>
            </div>

```
        <div id="myGrid" style="width:100%;height:350px;"></div>
        <div id="pager" style="width:100%;height:20px;"></div>
    </div>
```

Have you tried this approach?

**Comment by elGecko** [comment]
I just tried it. Now it works :) Thank you!
