### ISSUE TITLE
Are you going to branch from SlickGrid 2.0?

### ISSUE THREAD

**Issue by CoffeeJerk** [JLynch7/SlickGrid#7]
mliebman appears to have posted a newer version of SlickGrid than 2.0 Alpha, as shown in his examples. Do you plan on branching from the newer version?
We need to use your version, with frozen columns, for our application, so we have been using your branch (which we like very much, thank you!).

**Comment by sipte** [comment]
Yes, can you please merge, I tried doing that using beyond compare, but too many changes and I feel I might break something.

**Comment by JLynch7** [comment]
I'll try to merge with the latest this weekend

**Comment by sipte** [comment]
any luck on this JLynch7, thanks

**Comment by JLynch7** [comment]
Still working on it.  Probably about 75% complete.

**Comment by JLynch7** [comment]
Finally merged

**Comment by sipte** [comment]
excellent, thank you

**Comment by CoffeeJerk** [comment]
I assumed that you were going to merge WITH frozen columns. But I do not see any frozen column code in your version. Please explain!
Thanks!

**Comment by JLynch7** [comment]
I keep the frozen rows & columns code in a separate branch (https://github.com/JLynch7/SlickGrid/tree/2.0-frozenRowsAndColumns)

**Comment by CoffeeJerk** [comment]
Thank you, that explains everything. I was pulling from the wrong branch.
- Mike
  On May 30, 2012, at 4:57 PM, JLynch7 wrote:

> I keep the frozen rows & columns code in a separate branch (https://github.com/JLynch7/SlickGrid/tree/2.0-frozenRowsAndColumns)
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/JLynch7/SlickGrid/issues/7#issuecomment-6021123

Michael Berger
Senior User Interface Designer and Developer
mberger@mit.edu
