### ISSUE TITLE
Will there be plans to merge this into SlickGrid 2.0

### ISSUE THREAD

**Issue by ppong** [JLynch7/SlickGrid#8]
I really like the frozen column feature you have implemented. I am just wondering if there is any plans to merge this into mleibman/SlickGrid in the near future?

Thanks!

**Comment by Kallin** [comment]
+1! I'd love to see this merged into the mainline.

**Comment by ghost** [comment]
+1 Would also like to see it merged.

**Comment by danielsimons1** [comment]
+1 This is a very useful feature.

**Comment by Celebio** [comment]
+1, I need this one.

**Comment by JLynch7** [comment]
See https://github.com/mleibman/SlickGrid/issues/208 for more detail
