### ISSUE TITLE
frozen columns and non-frozen columns offset when scroll down in frozen columns in IE8 and IE9

### ISSUE THREAD

**Issue by alanchowky** [JLynch7/SlickGrid#9]
When I try to use the grid in the IE8 and IE9 and scroll down in the frozen columns, I found that the there would be an row offset between frozen columns and non-frozen columns. 

http://jlynch7.github.com/SlickGrid/examples/example-frozen-columns.html

**Comment by JLynch7** [comment]
I'm having trouble reproducing this issue.  Can you give a more specific list of steps?

**Comment by alanchowky** [comment]
I found that it appears only on the IE8. I tried using the Browser Mode to IE8 in the IE9 developer tools.

Try to scroll using mousewheel in the frozen columns.
http://jlynch7.github.com/SlickGrid/examples/example-frozen-columns.html
